### ISSUE TITLE
better error handling

### ISSUE THREAD

**Issue by rybbchao** [ray846/fops#3]
It seems that you handled errors yourself, e.g. [cmd/helper.go#L51](https://github.com/ray846/fops/blob/9f6073e05a7473b8e159340d5ac9e6497bdd4a70/cmd/helper.go#L51).
Try returning errors and use the `cobra`'s hook `RunE` to handle them. It's a good practice that handle errors in the same place at higher level function.

**Comment by ray846** [comment]
I tried to fix this issue on [different branch](https://github.com/ray846/fops/commit/91b711a7d91f0ecc0991b8f88d7aeec5b3de5b57).

**Comment by rybbchao** [comment]
Thanks for the commits.

The `else if` statement here is redundant because `err != nil` if `valid == false`.

[cmd/checksum.go#L55](https://github.com/ray846/fops/blob/9f1e846ecffab36a827a265d97c70b6f9e38c371/cmd/checksum.go#L55)

```go
valid, err := fileinfo.IsValidFile(inputFile, true)
if err != nil {
	return err
} else if !valid {
	return err
}
```

**Comment by cheyilin** [comment]
Hi @ray846,

If recent commits have met the requirement, please leave a comment here so @rybbchao can review the changes and close this issue. Thanks.

**Comment by ray846** [comment]
@rybbchao 
Thanks for your replied.
I deleted the redundant codes.

**Comment by rybbchao** [comment]
Reviewed, thanks for the fixes. Close now.
