### ISSUE TITLE
Few improvement suggestions

### ISSUE THREAD

**Issue by HongChenTW** [ray846/fops#4]
Hi @ray846, this is Hong from Trend Micro, thanks for your work and there are some improvement suggestions:

### Bug

- `linecount` command returns unexpectedly result
When test with `test/test.js` & `test/test.json`, the command results return less than real line count, I think it's related to `EOL` conditions [1].

It will be great if the test cases could also be enriched.

---

### Improvements (optional)

1. readability
https://github.com/ray846/fops/blob/9f1e846ecffab36a827a265d97c70b6f9e38c371/cmd/checksum.go#L82-L90

If first condition is fulfilled and coming with return statement, you can directly finish this `if` statement and start a new one, this is known as `Guard`[2]

For example:
```go
for _, i := range algorithms {
	choose, err := cmd.Flags().GetBool(i.name)
	if err != nil {
		return nil, nil
	}
	if choose {
		count++
		theChosenOne = i.hash
	}
}
```

If the project becomes larger, there might have more conditions, this will help other engineers to read your code easily.

2. some errors had been ignored
https://github.com/ray846/fops/blob/9f1e846ecffab36a827a265d97c70b6f9e38c371/cmd/checksum.go#L85

---

### References
- [1] https://stackoverflow.com/a/16224292/5217966
- [2] https://en.wikipedia.org/wiki/Guard_(computer_science)

**Comment by ray846** [comment]
Thank you for attaching references. They're super helpful!

**Comment by HongChenTW** [comment]
No problem, please merge both branches(`guard` & `lineCount`) into `main` branch and notice me when you're ready.

**Comment by HongChenTW** [comment]
Hi @ray846 , haven't heard from you for a while, but I think the recent commits are good enough to close this issue.
